services:
  edgedb:
    image: geldata/gel:6.4
    environment:
      GEL_SERVER_TLS_CERT_MODE: ${GEL_SERVER_TLS_CERT_MODE}
      GEL_SERVER_SECURITY: ${GEL_SERVER_SECURITY}
      GEL_SERVER_ADMIN_UI: ${GEL_SERVER_ADMIN_UI}
      GEL_SERVER_USER: ${GEL_USER}
      GEL_SERVER_PASSWORD: ${GEL_PASSWORD}
    volumes:
      - edgedb_data:/var/lib/gel/data  # Usando volume do Docker
      - ./db/edgedb/dbschema:/dbschema
#      - ./db/edgedb/data:/var/lib/edgedb/data
      - ./db/edgedb/cli_config:/.config/edgedb
    ports:
      - "${GEL_PORT}:5656"
    networks:
      - internal-network

  qdrant:
    image: "qdrant/qdrant:latest"
    ports:
      - "${QDRANT_PORT}:6333"
    volumes:
      - ./db/qdrant:/qdrant/storage
    networks:
      - internal-network

  api:
    image: otimizai.azurecr.io/vectorhubclient:latest
    # image: otimizai/vectorhub-client:latest
    ports:
      - "${API_CLIENT_BACKEND_PORT}:8081"
    volumes:
      - ./__workdir__:/app/__workdir__
    depends_on:
      - qdrant
      - edgedb
    networks:
      - internal-network
      - external-network
    env_file:
      - .env
    environment:
      TYPE_ENV: ${TYPE_ENV}
      SECRET_KEY_ADMIN: ${SECRET_KEY_ADMIN}
      REDIS_HOST: redis
      REDIS_PORT: 5050
      QDRANT_HOST: qdrant
      QDRANT_PORT: ${QDRANT_PORT}
      EDGEDB_HOST: edgedb
      EDGEDB_PORT: ${GEL_PORT}
      EDGEDB_PASSWORD: ${GEL_PASSWORD}


volumes:
  edgedb_data:  # Definição correta do volume
    driver: local
  redis_data:
    driver: local
  qdrant_storage:
    driver: local
  api_data:
    driver: local

networks:
  internal-network:
    driver: bridge
  external-network:
    driver: bridge